name: Release

on:
  workflow_dispatch:
    inputs:
        releaseTag:
            description: 'Release Tag'     
            required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - run: npm install
        - run: npm run build && npm publish
        - name: Bump version and create release
          id: release
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: ${{ github.event.inputs.releaseTag }}
