name: Release

on:
  workflow_dispatch:
    inputs:
        releaseTag:
            description: 'Release Tag'     
            required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org'
        - name: Install dependencies and build
          run: |
            npm install
            npm install -g rollup
            npm install -g terser
            npm run build
        - name: Publish package on NPM 📦
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: Create Github release
          id: release
          uses: softprops/action-gh-release@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: ${{ github.event.inputs.releaseTag }}
